# Generated by Django 4.2.13 on 2024-06-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_country_remove_city_point_delete_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
