# Generated by Django 4.2.13 on 2024-06-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='blog',
        ),
    ]
